collections:
- infra.aap_configuration
- infra.aap_utilities
- infra.ah_configuration
- infra.ansible_rekey_variables
- infra.controller_configuration
- infra.convert2rhel
- infra.eda_configuration
- infra.ee_utilities
- infra.leapp
- infra.lvm_snapshots
- infra.middleware_ocpv
- infra.osbuild
- ansible.controller
- ansible.eda
- ansible.hub
- ansible.netcommon
- ansible.network
- ansible.platform
- ansible.posix
- ansible.receptor
- ansible.scm
- ansible.security
- ansible.snmp
- ansible.utils
- ansible.windows
- ansible.yang
- arista.avd
- arista.cvp
- arista.dmf
- arista.eos
- chocolatey.chocolatey
- cohesity.dataprotect
- citrix.adc
- cisco.aci
- cisco.asa
- cisco.dcnm
- cisco.dnac
- cisco.intersight
- cisco.ios
- cisco.iosxr
- cisco.ise
- cisco.meraki
- cisco.mso
- cisco.nd
- cisco.nxos
- confluent.platform
- cloud.vmware_ops
- cloud.common
- cloud.terraform
- cloud.terraform_ops

